### PR TITLE
release: sourcegraph@5.0.4

### PR DESCRIPTION
**Pull request by camdencheek**
This pull request is part of the Sourcegraph 5.0.4 release.

* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/52092)

### Test plan

CI checks in this repository should pass, and a manual review should confirm if the generated changes are correct.

### CODE REVIEW

**Comment by camdencheek** [comment]
@sourcegraph/release-guild this repo is new since I've last released. Does this replace the customer replica branch? And should it contain the new embeddings service?

**Comment by coury-clark** [comment]
@camdencheek yes, this replaces the branch. I have no idea if it should have the embeddings service, other than to say if github.com/sourcegraph/deploy-sourcegraph-docker has it, this should have it too

**Comment by camdencheek** [comment]
@coury-clark is there still some concept of "changes unrelated to upgrade" in this repo? Or can I just copy over the changes from deploy-sourcegraph-docker into this PR?

**Comment by coury-clark** [comment]
@camdencheek you shouldn't need to do anything, this PR should be complete from the release tool

**Review by unknwon — APPROVED** [review]
We were fine just mering it https://github.com/sourcegraph/deploy-sourcegraph-docker-customer-replica-1/pull/31

**Comment by camdencheek** [comment]
Just to triple check: there was just [a PR](https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/921) backported into the `deploy-sourcegraph-docker` 5.0 branch that contains the new embeddings service. No equivalent PR was merged into this repo. Should there be?

**Comment by coury-clark** [comment]
@camdencheek got it, yes there should be. That PR should have been duplicated into this repo, so we will need to manually add it here and into main

**Comment by camdencheek** [comment]
Great, thanks for confirming!

**Comment by coury-clark** [comment]
Sorry for the confusion! PRs in the main docker repo have this checklist, but it looks like it got deleted (or not used) when the PR was made

**Comment by camdencheek** [comment]
@jac: I've taken a stab at porting the embeddings service to pure docker. Could you please take a look?

**Comment by jac** [comment]
@camdencheek tested it locally and it works fine 👍 
The Embeddings service is disabled by default in the other deployment methods (high resource requests, only necessary if using Cody). It might make sense to do the same here too

**Pull request merged**
